spring:
  application:
    name: demo

  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://admin:review123@52.231.26.114:27017
      database: REVIEW_EARLY


  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1234

server:
  port: 8080

mybatis:
  config-location: classpath:mybatis/configuration.xml